/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamCompleteRouteImport } from './routes/exam-complete'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardMyExamsRouteImport } from './routes/dashboard.my-exams'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardExamsRouteImport } from './routes/dashboard.exams'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard.certificates'
import { Route as CertificateCredentialIdRouteImport } from './routes/certificate.$credentialId'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminAiGeneratorRouteImport } from './routes/admin.ai-generator'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminExamsIndexRouteImport } from './routes/admin.exams.index'
import { Route as DashboardExamAttemptIdRouteImport } from './routes/dashboard.exam.$attemptId'
import { Route as DashboardExamWaitingExamIdRouteImport } from './routes/dashboard.exam-waiting.$examId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminExamsNewRouteImport } from './routes/admin.exams.new'
import { Route as AdminExamsExamIdRouteImport } from './routes/admin.exams.$examId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCompleteRoute = ExamCompleteRouteImport.update({
  id: '/exam-complete',
  path: '/exam-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyExamsRoute = DashboardMyExamsRouteImport.update({
  id: '/my-exams',
  path: '/my-exams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamsRoute = DashboardExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const CertificateCredentialIdRoute = CertificateCredentialIdRouteImport.update({
  id: '/certificate/$credentialId',
  path: '/certificate/$credentialId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiGeneratorRoute = AdminAiGeneratorRouteImport.update({
  id: '/ai-generator',
  path: '/ai-generator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminExamsIndexRoute = AdminExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminExamsRoute,
} as any)
const DashboardExamAttemptIdRoute = DashboardExamAttemptIdRouteImport.update({
  id: '/exam/$attemptId',
  path: '/exam/$attemptId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamWaitingExamIdRoute =
  DashboardExamWaitingExamIdRouteImport.update({
    id: '/exam-waiting/$examId',
    path: '/exam-waiting/$examId',
    getParentRoute: () => DashboardRoute,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminExamsNewRoute = AdminExamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminExamsRoute,
} as any)
const AdminExamsExamIdRoute = AdminExamsExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => AdminExamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/exam-complete': typeof ExamCompleteRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/ai-generator': typeof AdminAiGeneratorRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/vouchers': typeof AdminVouchersRoute
  '/certificate/$credentialId': typeof CertificateCredentialIdRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/my-exams': typeof DashboardMyExamsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/dashboard/exam-waiting/$examId': typeof DashboardExamWaitingExamIdRoute
  '/dashboard/exam/$attemptId': typeof DashboardExamAttemptIdRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/exam-complete': typeof ExamCompleteRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/ai-generator': typeof AdminAiGeneratorRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/certificate/$credentialId': typeof CertificateCredentialIdRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/my-exams': typeof DashboardMyExamsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/dashboard/exam-waiting/$examId': typeof DashboardExamWaitingExamIdRoute
  '/dashboard/exam/$attemptId': typeof DashboardExamAttemptIdRoute
  '/admin/exams': typeof AdminExamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/exam-complete': typeof ExamCompleteRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/ai-generator': typeof AdminAiGeneratorRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/vouchers': typeof AdminVouchersRoute
  '/certificate/$credentialId': typeof CertificateCredentialIdRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/my-exams': typeof DashboardMyExamsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/dashboard/exam-waiting/$examId': typeof DashboardExamWaitingExamIdRoute
  '/dashboard/exam/$attemptId': typeof DashboardExamAttemptIdRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/exam-complete'
    | '/login'
    | '/payment-success'
    | '/register'
    | '/verify-otp'
    | '/admin/ai-generator'
    | '/admin/certificates'
    | '/admin/exams'
    | '/admin/monitoring'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vouchers'
    | '/certificate/$credentialId'
    | '/dashboard/certificates'
    | '/dashboard/exams'
    | '/dashboard/history'
    | '/dashboard/my-exams'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/admin/'
    | '/dashboard/'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/users/$userId'
    | '/dashboard/exam-waiting/$examId'
    | '/dashboard/exam/$attemptId'
    | '/admin/exams/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/exam-complete'
    | '/login'
    | '/payment-success'
    | '/register'
    | '/verify-otp'
    | '/admin/ai-generator'
    | '/admin/certificates'
    | '/admin/monitoring'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/vouchers'
    | '/certificate/$credentialId'
    | '/dashboard/certificates'
    | '/dashboard/exams'
    | '/dashboard/history'
    | '/dashboard/my-exams'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/admin'
    | '/dashboard'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/users/$userId'
    | '/dashboard/exam-waiting/$examId'
    | '/dashboard/exam/$attemptId'
    | '/admin/exams'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/exam-complete'
    | '/login'
    | '/payment-success'
    | '/register'
    | '/verify-otp'
    | '/admin/ai-generator'
    | '/admin/certificates'
    | '/admin/exams'
    | '/admin/monitoring'
    | '/admin/payments'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vouchers'
    | '/certificate/$credentialId'
    | '/dashboard/certificates'
    | '/dashboard/exams'
    | '/dashboard/history'
    | '/dashboard/my-exams'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/admin/'
    | '/dashboard/'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/users/$userId'
    | '/dashboard/exam-waiting/$examId'
    | '/dashboard/exam/$attemptId'
    | '/admin/exams/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExamCompleteRoute: typeof ExamCompleteRoute
  LoginRoute: typeof LoginRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  RegisterRoute: typeof RegisterRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  CertificateCredentialIdRoute: typeof CertificateCredentialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-complete': {
      id: '/exam-complete'
      path: '/exam-complete'
      fullPath: '/exam-complete'
      preLoaderRoute: typeof ExamCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-exams': {
      id: '/dashboard/my-exams'
      path: '/my-exams'
      fullPath: '/dashboard/my-exams'
      preLoaderRoute: typeof DashboardMyExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exams': {
      id: '/dashboard/exams'
      path: '/exams'
      fullPath: '/dashboard/exams'
      preLoaderRoute: typeof DashboardExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/certificate/$credentialId': {
      id: '/certificate/$credentialId'
      path: '/certificate/$credentialId'
      fullPath: '/certificate/$credentialId'
      preLoaderRoute: typeof CertificateCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-generator': {
      id: '/admin/ai-generator'
      path: '/ai-generator'
      fullPath: '/admin/ai-generator'
      preLoaderRoute: typeof AdminAiGeneratorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/exams/': {
      id: '/admin/exams/'
      path: '/'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AdminExamsIndexRouteImport
      parentRoute: typeof AdminExamsRoute
    }
    '/dashboard/exam/$attemptId': {
      id: '/dashboard/exam/$attemptId'
      path: '/exam/$attemptId'
      fullPath: '/dashboard/exam/$attemptId'
      preLoaderRoute: typeof DashboardExamAttemptIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exam-waiting/$examId': {
      id: '/dashboard/exam-waiting/$examId'
      path: '/exam-waiting/$examId'
      fullPath: '/dashboard/exam-waiting/$examId'
      preLoaderRoute: typeof DashboardExamWaitingExamIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/exams/new': {
      id: '/admin/exams/new'
      path: '/new'
      fullPath: '/admin/exams/new'
      preLoaderRoute: typeof AdminExamsNewRouteImport
      parentRoute: typeof AdminExamsRoute
    }
    '/admin/exams/$examId': {
      id: '/admin/exams/$examId'
      path: '/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AdminExamsExamIdRouteImport
      parentRoute: typeof AdminExamsRoute
    }
  }
}

interface AdminExamsRouteChildren {
  AdminExamsExamIdRoute: typeof AdminExamsExamIdRoute
  AdminExamsNewRoute: typeof AdminExamsNewRoute
  AdminExamsIndexRoute: typeof AdminExamsIndexRoute
}

const AdminExamsRouteChildren: AdminExamsRouteChildren = {
  AdminExamsExamIdRoute: AdminExamsExamIdRoute,
  AdminExamsNewRoute: AdminExamsNewRoute,
  AdminExamsIndexRoute: AdminExamsIndexRoute,
}

const AdminExamsRouteWithChildren = AdminExamsRoute._addFileChildren(
  AdminExamsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAiGeneratorRoute: typeof AdminAiGeneratorRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminExamsRoute: typeof AdminExamsRouteWithChildren
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminVouchersRoute: typeof AdminVouchersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiGeneratorRoute: AdminAiGeneratorRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminExamsRoute: AdminExamsRouteWithChildren,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminVouchersRoute: AdminVouchersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardExamsRoute: typeof DashboardExamsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardMyExamsRoute: typeof DashboardMyExamsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardExamWaitingExamIdRoute: typeof DashboardExamWaitingExamIdRoute
  DashboardExamAttemptIdRoute: typeof DashboardExamAttemptIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardExamsRoute: DashboardExamsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardMyExamsRoute: DashboardMyExamsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardExamWaitingExamIdRoute: DashboardExamWaitingExamIdRoute,
  DashboardExamAttemptIdRoute: DashboardExamAttemptIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExamCompleteRoute: ExamCompleteRoute,
  LoginRoute: LoginRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  RegisterRoute: RegisterRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  CertificateCredentialIdRoute: CertificateCredentialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
